apiVersion: v1
kind: Service
metadata:
  name: dns-resolver-dns
  labels:
    app: dns-resolver
spec:
  selector:
    app: dns-resolver
  ports:
    - name: dns-udp
      port: 53
      targetPort: 5353
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 5353
      protocol: TCP
    - name: dot
      port: 853
      targetPort: 8853
      protocol: TCP
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: dns-resolver-http
  labels:
    app: dns-resolver
spec:
  selector:
    app: dns-resolver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
